jwt.secret=${JWT_SECRET}
JWT_SECRET=4f2b9d8e1c6a73b5a9e4c2d1f8b7a6c5d3e9f1a4b8c6d2e7f5a1c9b3d6e8f2a7

jwt.access-expiration-seconds=900
jwt.refresh-expiration-seconds=604800
jwt.header=Authorization
jwt.prefix=Bearer
jwt.issuer=jwt-token-example
jwt.audience=jwt-token-example-client

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jwtdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=${DB_USERNAME:harsh}
spring.datasource.password=${DB_PASSWORD:harsh123}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Maximum time a connection can sit idle (in milliseconds)
spring.datasource.hikari.idle-timeout=300000

# Maximum lifetime of a connection in the pool
spring.datasource.hikari.max-lifetime=600000

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
